import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import VideoModal from '@/components/modal/video-modal';
import { VideoProvider } from '@/contexts/video-context';

const roboto = Roboto({ subsets: ['vietnamese'], weight: ['400', '500', '700', '900'] });

export const metadata: Metadata = {
    title: 'SPOC',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${roboto.className} antialiased`}>
                <VideoProvider>
                    {children}
                    <VideoModal />
                </VideoProvider>
            </body>
        </html>
    );
}
